version: '3.1'
services:
  db:
    ports:
      - "5433:5432"
    expose:
      - "5433"
    build: ./database
    restart: always
  pedidoservice:
    depends_on:
      - db
    container_name: pedido-postgresql
    image: pedido
    ports:
      - "9000:9000"
    build: ./
volumes:
  postgres-data:

